### ISSUE TITLE
Cuda out of memory error

### ISSUE THREAD

**Issue by Yasmin-Kassim** [djimenezsanchez/NaroNet#2]
I'm trying the example of 'Endometrial_POLE', I have changed PCL_batch_size from 80 to 8 and it is still not woring given that my GPU memory is about 16 GB 

![image](https://user-images.githubusercontent.com/16782894/217067247-737a199d-c9db-4210-8689-1de3c577f928.png)

![image](https://user-images.githubusercontent.com/16782894/217067028-dd18b26e-aed1-4cdf-9fc6-84a1b4566a92.png)

In your documentation, it is saying that I can change the args['PCL_N_Crops_per_Image'] parameter but I can not see this parameter in the code
![image](https://user-images.githubusercontent.com/16782894/217067677-72105568-d9e2-42c7-ad28-9cf893ced8ad.png)

Please advise what to do, what other parameters I'm supposed to change to make it work given that I'm emptying my gpu RAM before each run and I'm making sure that there were no "zombies" :)
Thanks

**Comment by djimenezsanchez** [comment]
Hello Yasmin!

Thanks for your detailed explanation. I'm looking into it!

To assess your situation better could you tell me your cuda version? You can simply send me the outputs of "nvidia-smi" and "nvcc --version".

Best
Daniel

**Comment by Yasmin-Kassim** [comment]
Here is the nvidia-smi output
![image](https://user-images.githubusercontent.com/16782894/217386849-e0521f93-4a65-4114-a55f-d4ecc0f353ae.png)

I'm using anaconda inside WSL with Ubuntu 18.04 and both tensorflow and pytorch are recognizing the GPU in my env

![image](https://user-images.githubusercontent.com/16782894/217387343-94dd365e-dad8-4d8b-b42c-f09f5c7bb797.png)

Thanks
Yasmin

**Comment by djimenezsanchez** [comment]
Hello Yasmin, 

I've tried to reproduce the "example_POLE" experiment using my personal laptop which has a 6GB GPU. 

I achieved to do it, but to do so I had to change the CNN from a ResNet-101 to a ResNet-50. In args['PCL_depth_CNN'] write 50 instead of 101 to select ResNet-50. 

![image](https://user-images.githubusercontent.com/43730952/218209057-17ec0b44-27a4-424d-b8ab-20699e64b393.png)

In past experiments, I've tried both ResNet-50 and ResNet-101 in and showed similar performance. 

Please let me know if you encounter any more issues. You can reduce PCL_depth_CNN to 1 if you need to reduce memory required by the CNN. In this module, the most relevant parameter is the batch size, where its reduction will decrease the performance of feature extraction notably. 

PS. I updated the README, as the information displayed did not correspond to this version of the code. Sorry for the inconvenience.

Best,
Daniel
